import type { Contract, Set } from "@icon-sheets/schema";

import type { OutputFile } from "./types";

/** Pretty JSON — also a valid JavaScript expression, so it doubles as the emitted literal. */
const json = (value: unknown): string => JSON.stringify(value, null, 2);

/** The banner atop every emitted module, naming the contract it was built from. */
const banner = (id: string): string =>
  `// Generated by @icon-sheets/kit from ${JSON.stringify(id)}. Do not edit by hand.`;

/** A string-literal union, one member per line; `never` when empty. Follows a bare `=`. */
const union = (members: string[]): string =>
  members.length === 0
    ? " never"
    : members.map((member) => `\n  | ${JSON.stringify(member)}`).join("");

/**
 * A module and its declarations, emitted side by side. `.d.mts` is what
 * TypeScript pairs with an `.mjs` under every module resolution, including a
 * relative `import "./icons/config.mjs"` in an app.
 */
const pair = (name: string, mjs: string[], dts: string[]): OutputFile[] => [
  { path: `${name}.mjs`, contents: `${mjs.join("\n")}\n` },
  { path: `${name}.d.mts`, contents: `${dts.join("\n")}\n` },
];

/**
 * The root entry: the alias list and its guard, the set ids, and the `href`
 * helper that applies the id prefix. Carries no icon data, so importing the
 * guard never pulls the contract or a sheet into a bundle.
 */
export const emitIndex = (
  id: string,
  aliases: string[],
  setIds: string[],
  prefix: string,
): OutputFile[] =>
  pair(
    "index",
    [
      banner(id),
      `export const prefix = ${JSON.stringify(prefix)};`,
      `export const aliases = Object.freeze(${json(aliases)});`,
      `export const setIds = Object.freeze(${json(setIds)});`,
      "const known = new Set(aliases);",
      `export const isAlias = (value) => typeof value === "string" && known.has(value);`,
      "export const href = (alias) => `#${prefix}${alias}`;",
    ],
    [
      banner(id),
      `export type Alias =${union(aliases)};`,
      `export type SetId =${union(setIds)};`,
      `export declare const prefix: ${JSON.stringify(prefix)};`,
      "export declare const aliases: readonly Alias[];",
      "export declare const setIds: readonly SetId[];",
      "export declare const isAlias: (value: unknown) => value is Alias;",
      `export declare const href: <A extends Alias>(alias: A) => \`#${prefix}\${A}\`;`,
    ],
  );

/**
 * The `./config` entry: the resolved contract, and the `{ contract }` config
 * `useIconSheetsConfig` seeds a runtime container from. Plain data — no runtime
 * import of icon-sheets — typed against the exact alias union.
 */
export const emitConfig = (contract: Contract): OutputFile[] =>
  pair(
    "config",
    [
      banner(contract.id),
      `export const contract = ${json(contract)};`,
      "export default { contract };",
    ],
    [
      banner(contract.id),
      'import type { IconifyIcon, Identity } from "icon-sheets";',
      'import type { IconSheetsConfig } from "icon-sheets/config";',
      'import type { Alias } from "./index.mjs";',
      "export type Contract = Identity & { icons: Record<Alias, IconifyIcon> };",
      "export declare const contract: Contract;",
      "declare const config: IconSheetsConfig<Contract>;",
      "export default config;",
    ],
  );

/**
 * The `./sheet` entry: the base sheet markup as the default export, and each
 * set's sheet (the base with the set's rebinds on top) keyed by set id. Hidden
 * sprites, ready to inline into a page.
 */
export const emitSheet = (
  id: string,
  base: string,
  sheets: Record<string, string>,
): OutputFile[] =>
  pair(
    "sheet",
    [
      banner(id),
      `export const sheets = Object.freeze(${json(sheets)});`,
      `export default ${JSON.stringify(base)};`,
    ],
    [
      banner(id),
      'import type { SetId } from "./index.mjs";',
      "export declare const sheets: { readonly [K in SetId]: string };",
      "declare const sheet: string;",
      "export default sheet;",
    ],
  );

/**
 * The `./sets` entry: each resolved Set document keyed by its id, ready for a
 * runtime service's `apply`.
 */
export const emitSets = (id: string, sets: Set[]): OutputFile[] => {
  const keyed = Object.fromEntries(sets.map((set) => [set.id, set]));
  return pair(
    "sets",
    [
      banner(id),
      `export const sets = Object.freeze(${json(keyed)});`,
      "export default sets;",
    ],
    [
      banner(id),
      'import type { Set as IconSet } from "icon-sheets";',
      'import type { Alias, SetId } from "./index.mjs";',
      "export declare const sets: { readonly [K in SetId]: IconSet<Alias> };",
      "export default sets;",
    ],
  );
};
