import type { OutputFile } from "./types";

/**
 * Pretty JSON — also a valid JavaScript expression, so it doubles as the
 * literal an emitted module exports.
 */
export const json = (value: unknown): string => JSON.stringify(value, null, 2);

/** The banner atop every emitted module, naming the contract it was built from. */
export const banner = (id: string): string =>
  `// Generated by @icon-sheets/kit from ${JSON.stringify(id)}. Do not edit by hand.`;

/** A string-literal union, one member per line; `never` when empty. Follows a bare `=`. */
export const union = (members: string[]): string =>
  members.length === 0
    ? " never"
    : members.map((member) => `\n  | ${JSON.stringify(member)}`).join("");

/**
 * A module and its declarations, emitted side by side. `.d.mts` is what
 * TypeScript pairs with an `.mjs` under every module resolution, including a
 * relative `import "./icons/config.mjs"` in an app.
 *
 * @param name - The module's name, without an extension.
 * @param mjs - The module's source lines.
 * @param dts - The declaration's source lines.
 */
export const pair = (
  name: string,
  mjs: string[],
  dts: string[],
): OutputFile[] => [
  { path: `${name}.mjs`, contents: `${mjs.join("\n")}\n` },
  { path: `${name}.d.mts`, contents: `${dts.join("\n")}\n` },
];
