import type { Contract } from "@icon-sheets/schema";

import { serialize } from "./util";

/**
 * Renders the generated `icon-sheets.config.ts`: a header marking it generated, the
 * one import, and the configuration literal wrapping the resolved contract. The
 * consumer's TypeScript infers the alias union from the literal — full type
 * safety lands there, not here.
 *
 * @param contract - The resolved, validated contract.
 * @param source - A label for the header naming what it was generated from.
 */
export const emit = (contract: Contract, source: string): string => {
  const config = serialize({ contract }, "");
  return [
    "/**",
    ` * Generated by @icon-sheets/iconify from ${source}.`,
    " * Do not edit by hand — regenerate from the ref config.",
    " */",
    `import { defineIconSheetsConfig } from "@icon-sheets/icon-sheets/config";`,
    "",
    `export default defineIconSheetsConfig(${config});`,
    "",
  ].join("\n");
};
